remote_theme: athackst/jekyll-theme-profile

title: "Davide Orsucci"
description: "Personal website and portfolio"


profile_picture: /assets/images/profile.jpg   
author:
  name: "Davide Orsucci"
  email: "dade.orsu@gmail.com"

social_media:
  github: dadeorsu
  linkedin: davide-orsucci-206319250
