theme: jekyll-theme-cayman
title: "Davide Orsucci"
description: "Personal website and portfolio"
github:
  is_project_page: false
baseurl: "" 
url: "https://dadeorsu.github.io"  

github_username: dadeorsu
linkedin_username: davide-orsucci-206319250
